name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server (GitHub-hosted)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          script: |
            cd ${{ vars.APP_PATH }}
            echo "Deploying to production server..."
            git pull origin main
            composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-progress
